name: resturant
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  transparent_image: ^1.0.0
  url_launcher: ^5.0.2
  flutter_screenutil: ^0.4.2
  smooth_star_rating: 1.0.2
  flutter_swiper: ^1.1.4
  flutter_statusbarcolor: any
  superellipse_shape: ^0.1.5
  flutter_speed_dial: ^1.0.8
  google_maps_flutter: ^0.0.3+3
  flutter_google_places: ^0.1.4
  location: ^1.4.1
  rflutter_alert: ^1.0.2
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.2+1
  json_annotation: ^2.0.0
  font_awesome_flutter: ^8.4.0
  google_fonts_arabic: ^1.1.7
  cupertino_icons: ^0.1.2
  http: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/ic_launcher.png
    - assets/avatar_person.png
    - assets/drawerbg.jpg


  fonts:
    - family: Amiri
      fonts:
      - asset: assets/fonts/Amiri-Bold.ttf
      - asset: assets/fonts/Amiri-BoldItalic.ttf
      - asset: assets/fonts/Amiri-Italic.ttf
      - asset: assets/fonts/Amiri-Regular.ttf